"""add a persistent user table for oauth2

Revision ID: 047b2a6029ac
Revises: 05e696f0741c
Create Date: 2022-09-18 22:40:15.293793

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = '047b2a6029ac'
down_revision = '05e696f0741c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=1024), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('oauth_account',
                    sa.Column('oauth_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('access_token', sa.String(
                        length=1024), nullable=False),
                    sa.Column('expires_at', sa.Integer(), nullable=True),
                    sa.Column('refresh_token', sa.String(
                        length=1024), nullable=True),
                    sa.Column('account_id', sa.String(
                        length=320), nullable=False),
                    sa.Column('account_email', sa.String(
                        length=320), nullable=False),
                    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(),
                              nullable=False),
                    sa.Column(
                        'user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['user.id'], ondelete='cascade'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_oauth_account_account_id'),
                    'oauth_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_account_oauth_name'),
                    'oauth_account', ['oauth_name'], unique=False)
    op.add_column('downloads', sa.Column(
        'user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True))
    op.create_foreign_key(None, 'downloads', 'user', ['user_id'], ['id'])
    op.add_column('ratings', sa.Column(
        'user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True))
    op.drop_constraint('ratings_movie_id_ip_address_key',
                       'ratings', type_='unique')
    op.create_unique_constraint(
        None, 'ratings', ['movie_id', 'ip_address', 'user_id'])
    op.create_foreign_key(None, 'ratings', 'user', ['user_id'], ['id'])
    op.add_column('referrals', sa.Column(
        'user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True))
    op.create_foreign_key(None, 'referrals', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_column('referrals', 'user_id')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='unique')
    op.create_unique_constraint('ratings_movie_id_ip_address_key', 'ratings', [
                                'movie_id', 'ip_address'])
    op.drop_column('ratings', 'user_id')
    op.drop_constraint(None, 'downloads', type_='foreignkey')
    op.drop_column('downloads', 'user_id')
    op.drop_index(op.f('ix_oauth_account_oauth_name'),
                  table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'),
                  table_name='oauth_account')
    op.drop_table('oauth_account')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
