"""sixth revision: try to add music

Revision ID: 05e696f0741c
Revises: c4034c570dba
Create Date: 2020-12-11 19:17:14.693139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e696f0741c'
down_revision = 'c4034c570dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('artiste', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('collection', sa.String(), nullable=True),
    sa.Column('download_link', sa.String(), nullable=True),
    sa.Column('picture_link', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('source', 'download_link')
    )
    op.create_index(op.f('ix_music_index'), 'music', ['index'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_music_index'), table_name='music')
    op.drop_table('music')
    # ### end Alembic commands ###
