"""Second Revision

Revision ID: 9aa8146d6c94
Revises: e393bc2b5063
Create Date: 2020-05-03 14:49:05.260382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa8146d6c94'
down_revision = 'e393bc2b5063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloads_id'), 'downloads', ['id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.add_column('movies', sa.Column('description', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('download_link', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('referral_id', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('size', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'year')
    op.drop_column('movies', 'size')
    op.drop_column('movies', 'referral_id')
    op.drop_column('movies', 'download_link')
    op.drop_column('movies', 'description')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_downloads_id'), table_name='downloads')
    op.drop_table('downloads')
    # ### end Alembic commands ###
