"""fourth_revision: add new columns

Revision ID: 9f251721db16
Revises: c47920796331
Create Date: 2020-09-23 21:52:42.177117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f251721db16'
down_revision = 'c47920796331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('cast', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('category', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('imdb_link', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('is_series', sa.Boolean(), nullable=True))
    op.add_column('movies', sa.Column('quality', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('s_download_link', sa.JSON(), nullable=True))
    op.add_column('movies', sa.Column('subtitle_link', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('subtitle_links', sa.JSON(), nullable=True))
    op.add_column('movies', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('upload_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'upload_date')
    op.drop_column('movies', 'tags')
    op.drop_column('movies', 'subtitle_links')
    op.drop_column('movies', 'subtitle_link')
    op.drop_column('movies', 's_download_link')
    op.drop_column('movies', 'quality')
    op.drop_column('movies', 'is_series')
    op.drop_column('movies', 'imdb_link')
    op.drop_column('movies', 'category')
    op.drop_column('movies', 'cast')
    # ### end Alembic commands ###
