"""fifth revision: try to make listing a bit ordered

Revision ID: c4034c570dba
Revises: 9f251721db16
Create Date: 2020-09-26 00:47:48.257814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4034c570dba'
down_revision = '9f251721db16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('saved_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'saved_on')
    # ### end Alembic commands ###
