"""Third Revision

Revision ID: c47920796331
Revises: 9aa8146d6c94
Create Date: 2020-05-03 18:41:03.812708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47920796331'
down_revision = '9aa8146d6c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('cover_photo_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'cover_photo_link')
    # ### end Alembic commands ###
