namespace: gophie

labels:
  - pairs:
      app: ocena
      app.kubernetes.io/name: ocena
    includeSelectors: true
    includeTemplates: true
  - pairs:
      app.kubernetes.io/instance: ocena
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: gophie
    includeSelectors: false
    includeTemplates: true

resources:
  - deploy.yaml
  - ingress.yaml

